using System;
using System.Data;
using System.Data.OleDb; // 🚀 MS Access ke liye zaroori library
using System.Windows.Forms;

namespace StudyMatcher
{
    public partial class Match : Form
    {
        public Match()
        {
            InitializeComponent();
        }

        // 🚀 DATABASE LOAD: SELECT * lagaya hai taake column name ka koi error na aaye aur data load ho jaye
        private void Match_Load(object sender, EventArgs e)
        {
            string connString = @"Provider=Microsoft.ACE.OLEDB.12.0;Data Source=StudyMatcherDB.accdb;";

            // 🚀 FIXED QUERY: FullName mita kar * kar diya taake saare columns khud hi nikal aayein bina crash kiye
            string query = "SELECT * FROM Students";

            using (OleDbConnection conn = new OleDbConnection(connString))
            {
                try

                    // 1. DataGridView ko database records se fill karna
                    if (dataGridView1 != null)
                    {
                        dataGridView1.DataSource = dt;
                    }

                    // 2. ComboBox dropdown ko fill karna
                    if (comboBox1 != null)
                    {
                        comboBox1.DataSource = dt;

                        // 💡 SAFETY CHECK: Agar aapke database table mein column ka naam sirf 'Name' hai, 
                        // toh hum pehle check karte hain, warna jo bhi pehla column hoga wo display ho jayega.
                        if (dt.Columns.Contains("Name"))
                        {
                            comboBox1.DisplayMember = "Name";
                        }
                        else if (dt.Columns.Count > 0)
                        {
                            comboBox1.DisplayMember = dt.Columns[0].ColumnName; // Jo bhi pehla column ho (e.g. StudentName ya ID)
                        }
                    }
                }
                catch (Exception ex)
                {
                    // Agar database file na mile toh error show karega taake pata chale masla kya hai
                    MessageBox.Show("Error loading matched students from database: " + ex.Message, "DB Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
        }



        // 🔒 DESIGNER AUTOGENERATED FUNCTIONS (Bilkul touch nahi kiya, jaise the waise hi hain)
        private void label1_Click(object sender, EventArgs e) { }
        private void comboBox1_SelectedIndexChanged(object sender, EventArgs e) { }
    }
}